/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjekteRouteImport } from './routes/projekte'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KundenfeedbackRouteImport } from './routes/kundenfeedback'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as ForschungRouteImport } from './routes/forschung'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BueroRouteImport } from './routes/buero'
import { Route as BarrierefreiheitRouteImport } from './routes/barrierefreiheit'
import { Route as ArchitekturRouteImport } from './routes/architektur'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteRoute = ProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenfeedbackRoute = KundenfeedbackRouteImport.update({
  id: '/kundenfeedback',
  path: '/kundenfeedback',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const ForschungRoute = ForschungRouteImport.update({
  id: '/forschung',
  path: '/forschung',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BueroRoute = BueroRouteImport.update({
  id: '/buero',
  path: '/buero',
  getParentRoute: () => rootRouteImport,
} as any)
const BarrierefreiheitRoute = BarrierefreiheitRouteImport.update({
  id: '/barrierefreiheit',
  path: '/barrierefreiheit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitekturRoute = ArchitekturRouteImport.update({
  id: '/architektur',
  path: '/architektur',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architektur': typeof ArchitekturRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/buero': typeof BueroRoute
  '/datenschutz': typeof DatenschutzRoute
  '/forschung': typeof ForschungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kundenfeedback': typeof KundenfeedbackRoute
  '/leistungen': typeof LeistungenRoute
  '/projekte': typeof ProjekteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architektur': typeof ArchitekturRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/buero': typeof BueroRoute
  '/datenschutz': typeof DatenschutzRoute
  '/forschung': typeof ForschungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kundenfeedback': typeof KundenfeedbackRoute
  '/leistungen': typeof LeistungenRoute
  '/projekte': typeof ProjekteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architektur': typeof ArchitekturRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/buero': typeof BueroRoute
  '/datenschutz': typeof DatenschutzRoute
  '/forschung': typeof ForschungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kundenfeedback': typeof KundenfeedbackRoute
  '/leistungen': typeof LeistungenRoute
  '/projekte': typeof ProjekteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architektur'
    | '/barrierefreiheit'
    | '/buero'
    | '/datenschutz'
    | '/forschung'
    | '/impressum'
    | '/kontakt'
    | '/kundenfeedback'
    | '/leistungen'
    | '/projekte'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architektur'
    | '/barrierefreiheit'
    | '/buero'
    | '/datenschutz'
    | '/forschung'
    | '/impressum'
    | '/kontakt'
    | '/kundenfeedback'
    | '/leistungen'
    | '/projekte'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/architektur'
    | '/barrierefreiheit'
    | '/buero'
    | '/datenschutz'
    | '/forschung'
    | '/impressum'
    | '/kontakt'
    | '/kundenfeedback'
    | '/leistungen'
    | '/projekte'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitekturRoute: typeof ArchitekturRoute
  BarrierefreiheitRoute: typeof BarrierefreiheitRoute
  BueroRoute: typeof BueroRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ForschungRoute: typeof ForschungRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  KundenfeedbackRoute: typeof KundenfeedbackRoute
  LeistungenRoute: typeof LeistungenRoute
  ProjekteRoute: typeof ProjekteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte': {
      id: '/projekte'
      path: '/projekte'
      fullPath: '/projekte'
      preLoaderRoute: typeof ProjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundenfeedback': {
      id: '/kundenfeedback'
      path: '/kundenfeedback'
      fullPath: '/kundenfeedback'
      preLoaderRoute: typeof KundenfeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forschung': {
      id: '/forschung'
      path: '/forschung'
      fullPath: '/forschung'
      preLoaderRoute: typeof ForschungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buero': {
      id: '/buero'
      path: '/buero'
      fullPath: '/buero'
      preLoaderRoute: typeof BueroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barrierefreiheit': {
      id: '/barrierefreiheit'
      path: '/barrierefreiheit'
      fullPath: '/barrierefreiheit'
      preLoaderRoute: typeof BarrierefreiheitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architektur': {
      id: '/architektur'
      path: '/architektur'
      fullPath: '/architektur'
      preLoaderRoute: typeof ArchitekturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitekturRoute: ArchitekturRoute,
  BarrierefreiheitRoute: BarrierefreiheitRoute,
  BueroRoute: BueroRoute,
  DatenschutzRoute: DatenschutzRoute,
  ForschungRoute: ForschungRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  KundenfeedbackRoute: KundenfeedbackRoute,
  LeistungenRoute: LeistungenRoute,
  ProjekteRoute: ProjekteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
